# Generated by Django 2.2.24 on 2025-01-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    def fill_with_data_field_flat(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Flat.objects.filter(construction_year__gte=2015).update(
            new_building=True)

    dependencies = [
        ('property', '0004_auto_20250116_2222'),
    ]

    operations = [
        migrations.RunPython(fill_with_data_field_flat)
    ]
