# Generated by Django 2.2.24 on 2025-01-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    def fill_with_data_field_flat(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Flat.objects.filter(construction_year__gte=2015).update(
            new_building=True)
        Flat.objects.filter(construction_year__lt=2015).update(
            new_building=False)

    dependencies = [
        ('property', '0005_auto_20250116_2236'),
    ]

    operations = [
        migrations.RunPython(fill_with_data_field_flat)
    ]
