# Generated by Django 2.2.24 on 2025-01-18 12:42

from django.db import migrations
from django.db.models import F
from django.db import transaction
import phonenumbers


def parse_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    with transaction.atomic():
        for flat in flats:
            try:
                parsed_number = phonenumbers.parse(
                    flat.owners_phonenumber, 'RU')
                flat.owners_phonenumber = phonenumbers.format_number(
                    parsed_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
                flat.save()
            except Exception as e:
                print(f"Error parsing phone number for {flat.id}: {str(e)}")


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250118_1739'),
    ]

    operations = [
        migrations.RunPython(parse_phone)
    ]
