# Generated by Django 2.2.24 on 2025-01-19 15:35

from django.db import migrations
import phonenumbers
from django.db import transaction


class Migration(migrations.Migration):
    def parse_phone(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        flats = Flat.objects.all()
        with transaction.atomic():
            for flat in flats:
                try:
                    parsed_number = phonenumbers.parse(
                        flat.owners_phonenumber, 'RU')
                    flat.owner_pure_phone = phonenumbers.format_number(
                        parsed_number, phonenumbers.PhoneNumberFormat.E164)
                    flat.save()
                except Exception as e:
                    print(f"Error parsing phone number for {
                        flat.id}: {str(e)}"
                    )

    dependencies = [
        ('property', '0012_auto_20250118_1742'),
    ]

    operations = [
        migrations.RunPython(parse_phone)
    ]
